/**
 * BlockNumberedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockNumberedListItem : Block
{
    [JsonPropertyName("numbered_list_item")]
    public NumberedListItem? NumberedListItem { get; set; }

}

