/**
 * BlockPDF automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockPDF : Block
{
    [JsonPropertyName("pdf")]
    public PDF? Pdf { get; set; }

}

