/**
 * BlockParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockParentId : ParentId
{
    [JsonPropertyName("block_id")]
    public string? BlockId { get; set; }

}

