/**
 * Block automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(BlockBookmark), typeDiscriminator: "bookmark")]
[JsonDerivedType(typeof(BlockBreadcrumb), typeDiscriminator: "breadcrumb")]
[JsonDerivedType(typeof(BlockBulletedListItem), typeDiscriminator: "bulleted_list_item")]
[JsonDerivedType(typeof(BlockCallout), typeDiscriminator: "callout")]
[JsonDerivedType(typeof(BlockChildDatabase), typeDiscriminator: "child_database")]
[JsonDerivedType(typeof(BlockChildPage), typeDiscriminator: "child_page")]
[JsonDerivedType(typeof(BlockCode), typeDiscriminator: "code")]
[JsonDerivedType(typeof(BlockDivider), typeDiscriminator: "divider")]
[JsonDerivedType(typeof(BlockEmbed), typeDiscriminator: "embed")]
[JsonDerivedType(typeof(BlockEquation), typeDiscriminator: "equation")]
[JsonDerivedType(typeof(BlockFile), typeDiscriminator: "file")]
[JsonDerivedType(typeof(BlockHeading), typeDiscriminator: "heading_1")]
[JsonDerivedType(typeof(BlockHeading), typeDiscriminator: "heading_2")]
[JsonDerivedType(typeof(BlockHeading), typeDiscriminator: "heading_3")]
[JsonDerivedType(typeof(BlockImage), typeDiscriminator: "image")]
[JsonDerivedType(typeof(BlockNumberedListItem), typeDiscriminator: "numbered_list_item")]
[JsonDerivedType(typeof(BlockParagraph), typeDiscriminator: "paragraph")]
[JsonDerivedType(typeof(BlockPDF), typeDiscriminator: "pdf")]
[JsonDerivedType(typeof(BlockQuote), typeDiscriminator: "quote")]
public abstract class Block
{
    [JsonPropertyName("object")]
    public string? Object { get; set; }

    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("parent")]
    public ParentId? Parent { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("created_time")]
    public System.DateTime? CreatedTime { get; set; }

    [JsonPropertyName("created_by")]
    public User? CreatedBy { get; set; }

    [JsonPropertyName("last_edited_time")]
    public System.DateTime? LastEditedTime { get; set; }

    [JsonPropertyName("last_edited_by")]
    public User? LastEditedBy { get; set; }

    [JsonPropertyName("archived")]
    public bool? Archived { get; set; }

    [JsonPropertyName("in_trash")]
    public bool? InTrash { get; set; }

    [JsonPropertyName("has_children")]
    public bool? HasChildren { get; set; }

}

