/**
 * BlockBulletedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockBulletedListItem : Block
{
    [JsonPropertyName("bulleted_list_item")]
    public BulletedListItem? BulletedListItem { get; set; }

}

