/**
 * BlockBookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockBookmark : Block
{
    [JsonPropertyName("bookmark")]
    public Bookmark? Bookmark { get; set; }

}

