/**
 * BlockHeading3 automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockHeading : Block
{
    [JsonPropertyName("heading_3")]
    public BlockHeading? Heading { get; set; }

}

