/**
 * BlockLinkPreview automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class BlockLinkPreview
{
    [JsonPropertyName("link_preview")]
    public LinkPreview? LinkPreview { get; set; }

}

