/**
 * Bookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class Bookmark
{
    [JsonPropertyName("caption")]
    public System.Collections.Generic.List<RichText>? Caption { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

}

