/**
 * ChildDatabase automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class ChildDatabase
{
    [JsonPropertyName("title")]
    public string? Title { get; set; }

}

