/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Credentials;
using Sdkgen.Client.Exception;

namespace SdkFabric.Notion;

public class Client : ClientAbstract
{
    public Client(string baseUrl, ICredentials credentials) : base(baseUrl, credentials)
    {
    }

    public UsersTag Users()
    {
        return new UsersTag(
            this.HttpClient,
            this.Parser
        );
    }

    public DatabasesTag Databases()
    {
        return new DatabasesTag(
            this.HttpClient,
            this.Parser
        );
    }



    public static Client Build(string token)
    {
        return new Client("https://api.notion.com", new HttpBearer(token));
    }
}
