/**
 * Code automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class Code
{
    [JsonPropertyName("caption")]
    public System.Collections.Generic.List<RichText>? Caption { get; set; }

    [JsonPropertyName("rich_text")]
    public System.Collections.Generic.List<RichText>? RichText { get; set; }

    [JsonPropertyName("language")]
    public string? Language { get; set; }

}

