/**
 * Comment automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class Comment
{
    [JsonPropertyName("parent")]
    public ParentId? Parent { get; set; }

    [JsonPropertyName("discussion_id")]
    public string? DiscussionId { get; set; }

    [JsonPropertyName("rich_text")]
    public RichText? RichText { get; set; }

}

