/**
 * DatabaseCover automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class DatabaseCover
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("external")]
    public object? External { get; set; }

}

