/**
 * Database automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Notion;
public class Database
{
    [JsonPropertyName("object")]
    public string? Object { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("created_time")]
    public DateTime? CreatedTime { get; set; }
    [JsonPropertyName("last_edited_time")]
    public DateTime? LastEditedTime { get; set; }
    [JsonPropertyName("icon")]
    public DatabaseIcon? Icon { get; set; }
    [JsonPropertyName("cover")]
    public DatabaseCover? Cover { get; set; }
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    [JsonPropertyName("title")]
    public List<DatabaseTitle>? Title { get; set; }
    [JsonPropertyName("description")]
    public List<DatabaseTitle>? Description { get; set; }
}
