/**
 * File automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class File
{
    [JsonPropertyName("caption")]
    public System.Collections.Generic.List<RichText>? Caption { get; set; }

    [JsonPropertyName("file")]
    public FileObject? File { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

