/**
 * FileObject automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class FileObject
{
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("expiry_time")]
    public System.DateTime? ExpiryTime { get; set; }

}

