/**
 * Icon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(EmojiIcon), typeDiscriminator: "emoji")]
[JsonDerivedType(typeof(FileIcon), typeDiscriminator: "file")]
[JsonDerivedType(typeof(ExternalIcon), typeDiscriminator: "external")]
public abstract class Icon
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

