/**
 * ParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(DatabaseParentId), typeDiscriminator: "database_id")]
[JsonDerivedType(typeof(PageParentId), typeDiscriminator: "page_id")]
[JsonDerivedType(typeof(BlockParentId), typeDiscriminator: "block_id")]
[JsonDerivedType(typeof(WorkspaceParentId), typeDiscriminator: "workspace")]
public abstract class ParentId
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

