/**
 * PDF automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(PDFExternal), typeDiscriminator: "external")]
[JsonDerivedType(typeof(PDFFile), typeDiscriminator: "file")]
public abstract class PDF
{
    [JsonPropertyName("caption")]
    public System.Collections.Generic.List<RichText>? Caption { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

