/**
 * Text automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class Text
{
    [JsonPropertyName("content")]
    public string? Content { get; set; }

    [JsonPropertyName("link")]
    public Link? Link { get; set; }

}

