/**
 * WorkspaceParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Notion;

public class WorkspaceParentId : ParentId
{
    [JsonPropertyName("workspace")]
    public bool? Workspace { get; set; }

}

